spring:
  dataSource:
    driver-class-name: com.mysql.jdbc.ReplicationDriver
    url: jdbc:mysql:replication://localhost:3306,localhost:3306/message_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    initialSize: 3
    minIdle: 3
    maxActive: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
  redis:
    database: 0
    host: redis
    port: 6379
    # password: 123456
    pool:
      max-idle: 16
      min-idle: 4
      max-active: 40
      max-wait: -1
      timeout: 2000

flyway:
  baselineOnMigrate: true

dubbo:
  application:  # 提供方应用信息，用于计算依赖关系
    name: lemon-message
    owner: lonyee
    version: 1.0.0
    organization: lemon
    logger: slf4j
  provider:
    timeout: 3000
    retries: 1
    delay: -1
    threadpool: cached  # fixed 固定池 cached 缓存池 limited 增长池
  consumer:
    check: false
  registry:
    protocol: zookeeper
    address: zookeeper:2181
    check: false
    register: true
    subscribe: true
  annotation:
    package: cn.lemon.dubbo.message.service  # 扫描注解包路径，多个包用逗号分隔，不填pacakge表示扫描当前ApplicationContext中所有的类
  protocol:
    name: dubbo
    port: 20810
    accessLog: true

app:
  alisms:
    url: http://gw.api.taobao.com/router/rest
    appKey: 23579165
    appSecret: 8bc04e583c986b15aaca3b4729a260ec
    sign: 乐檬中国
  mail:
    host: smtp.yeah.net
    username: lemon_china@yeah.net
    password: qq123456
    default-encoding: UTF-8
    sign: 乐檬中国
  wechat:
    appId: wx7369c8fd2aa77079
    appSecret: 06294838b3533c7e8a485c61cbecc9b7
  rabbitmq:
    queuename: Q2
    exchange: exchange2
    addresses: rabbit:5672
    username: guest
    password: guest
    virtual-host: /

# 日志设定
logging:
  level:
    cn.lemon: DEBUG
  config: classpath:config/logback.xml
  path: /usr/logs/message
  

...